modLoader="javafml"
loaderVersion="[43,)"
license="MIT license"

[[mods]]
modId="more_locks"
version="${mod_version}"
displayName="MoreLocks"
authors="xXinailXx"
description=''''''

[[dependencies.more_locks]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.more_locks]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
